spring:
  datasource:
    url: jdbc:mariadb://poeking-db.cdyguk0isxgn.ap-northeast-2.rds.amazonaws.com:3306/poekingDB
    driver-class-name: org.mariadb.jdbc.Driver
    username: poeking
    password: poeking90
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update